service: Tramchester

provider:
  name: aws
  runtime: nodejs4.3

package:
  include:
    - index.js
    - node_modules/**
    - lib/**
    - data/**
  exclude:
    - package.json


functions:
  GetTrams:
    handler: index.handler
    events:
      - alexaSkill
    environment:
      TRAMCHESTER_APPID: ${env:TRAMCHESTER_APPID}
      TRAMCHESTER_DB: ${env:TRAMCHESTER_DB}
